#!/bin/bash

echo "Preparing proxy_wrapper"
sed -i "s/KUBERNETES_SERVICE_HOST/${KUBERNETES_SERVICE_HOST}/" /proxy_wrapper.sh

# As /etc/ssh is mounted from a persistent volume, need to copy sshd_config there
cp -f /sshd_config /etc/ssh
